### ISSUE TITLE
[WS] Stored procedures testing in phpmyadmin.

### ISSUE THREAD

**Issue by jericomanapsal** [jericomanapsal/genericqueueingsystem#21]
Test all stored procedures in phpmyadmin.

**Comment by Latisdorsi** [comment]
Removed 'serving' parameter from 'CreateCounter' procedure.
Removed 'serving' from table as well.

**Comment by Latisdorsi** [comment]
Change role into type to match 'type' parameter in procedure 'Create Customer'
INSERT INTO ... VALUES(username, password, name, [role], 'CUSTOMER');

**Comment by Latisdorsi** [comment]
Changed Procedure 'Login'
Changed user verification. Replaced user_id for verification and added 'exists' variable.
