### ISSUE TITLE
[WS] Web-Client Customer Queue Page Needed data

### ISSUE THREAD

**Issue by Latisdorsi** [jericomanapsal/genericqueueingsystem#34]
The queue displays the following data:
(Now Serving, Current Number, Counter, Brand, Branch)

Parameters to get data

- [session] from cookies to get the account id lined up for the queue

Expected data columns

- [(latest queues.number for specific counters.counter]
- [queues.number for customer]
- [counters.counter from queue.counter for customer] 
- [branches.brand from counters.branch for customer]
- [branches.branch from counters.branch for customer] 

Conditions:

- If customer is not lined up return an error status

**Comment by jericomanapsal** [comment]
issue done in latest merge
