### ISSUE TITLE
[WS] Web-Client Customer Search Page Needed Data

### ISSUE THREAD

**Issue by Latisdorsi** [jericomanapsal/genericqueueingsystem#35]
The search tables displays the following data:
(id, Brand, Branch, Category)

Parameters to get data
[Session]
[Two Types of Searching]
1. Brand Name Only
2. Brand Name and Branch

Expected data columns
- [branches.id]
- [branches.brand]
- [branches.branch]
- [branches.category]

**Comment by jericomanapsal** [comment]
Closed. Feature was removed during consultation
